### ISSUE TITLE
Next card number is generated when it shouldn't

### ISSUE THREAD

**Issue by intrueder** [MatskoVolodia/Kottans#3]
Pass the number `"4999999999999999993"` (VISA) into method `GenerateNextCreditCardNumber`
Expected result: exeption or some message like "no more card numbers available for this vendor"
Actual result: `"5000000000000000005"` (Maestro)

**Comment by MatskoVolodia** [comment]
One question. If we have similar case with correct VISA number that is the last correct code in 13(!)-characters format, should the next generated code be with 16 chars or exception?
Same question about Maestro.
